#

# skip_generalstats: true

###################################
## Custom content

custom_data:
    my_stats:
        file_format: 'csv'
        section_name: 'General Metrics'
        description: ''
        plot_type: 'table'
    thumbnail:
       section_name: "Thumbnail"

    cell_data:
       file_format: 'csv'
       section_name: 'Markers distribution'
       description: 'with a TPM value > 1 are considered. The number of expressed genes per sample was splitted into the 5 most abundant classes following the known gene annotations.'
       plot_type: 'table'

    correlation:
       file_format: 'csv'
       section_name: 'Markers pairwise correlation'
       description: 'plot showing the number of detected genes for a given set of subsampling values.'
       plot_type: 'heatmap'
       pconfig:
          min: -1
          max: 1
    my_methods:
      section_name: "Methods"
      plot_type: 'html'

sp:
   my_stats:
      fn: '*_stats.csv'
   thumbnail:
      fn: '*_thumbnail.png'
   cell_data:
      fn: '*_data.csv'
   correlation:
      fn: '*_heatmap.csv'
   my_methods:
      fn: '*_methods.html'


################################
## Clean sample names

fn_clean_exts:
  - '.ome'
  - '.tif'
  - '.qptif'
  - '.html'

###############################
## Modules 

module_order:
  - my_stats
  - thumbnail
  - cell_data
  - correlation
  - my_methods

custom_table_header_config:
  my_stats:
    "Cell number":
      format: '{:.0f}'
    "Tissue / Background area":
      format: '{:.2f}'
      suffix: "%"
    "Segmented Fraction":
      format: '{:.2f}'
      suffix: "%"
    "Minimal Size":
      format: '{:.0f}'
    "Maximal Size":
      format: '{:.0f}'
    "Necrotics cells":
      format: '{:.0f}'
    # Region of Interest

#############################
## Display

table_columns_visible:
    cell_data:
      X_centroid: false
      Y_centroid: false

plots_force_interactive: True
ignore_images: false
