#

# skip_generalstats: true

###################################
## Custom content

custom_data:
    my_stats:
        file_format: 'csv'
        section_name: 'General Metrics'
        description: ''
        plot_type: 'table'
        
    thumbnail:
       section_name: "Thumbnail"

    correlation:
       file_format: 'csv'
       section_name: 'Markers pairwise correlation'
       description: 'plot showing the number of detected genes for a given set of subsampling values.'
       plot_type: 'heatmap'
       pconfig:
          min: -1
          max: 1

sp:
   my_stats:
      fn: '*_stats.csv'
   thumbnail:
      fn: '*_thumbnail.png'
  #  cell-data:
  #     fn: '*_markers_distribution.html'
   correlation:
      fn: '*_heatmap.csv'


################################
## Clean sample names

fn_clean_exts:
  - '.ome'
  - '.tif'
  - '.qptif'
  - '.html'

###############################
## Modules 

module_order:
  - my_stats
  - thumbnail
  - cell-data
  - correlation
  - method-explanation

custom_table_header_config:
  my_stats:
    "Cell number":
      format: '{:.0f}'
    "Tissue / Background area":
      format: '{:.2f}'
      suffix: "%"
    "Segmented Fraction":
      format: '{:.2f}'
      suffix: "%"
    "Minimal Size":
      format: '{:.0f}'
    "Maximal Size":
      format: '{:.0f}'
    "Necrotics cells":
      format: '{:.0f}'
    # Region of Interest

#############################
## Display

# table_columns_visible:
#     cell_data:
#       X_centroid: false
#       Y_centroid: false

# plots_force_interactive: True
ignore_images: false
log_filesize_limit: 1000000000
